#!/usr/bin/env bash
# A Bash Script that installs installs nginx on my Web server
# Requirements:
# Install nginx on your web-01
# server
# Nginx should be listening on port 80
#
sudo apt-get update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
service nginx start
