#!/usr/bin/env bash
# Configures redirection in engine x
# install nginx
sudo apt-get update

sudo apt-get -y install nginx

# Starting nginx
service nginx start

# configuring nginx
current_conf="/etc/nginx/sites-available/default"

new_conf="
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html indx.htm index.nginx.debian.html;

        server_name _;

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"

echo "$new_conf" > "$current_conf"

# Set string to return
echo "Hello World!" > /var/www/html/index.html

# Restarting enginex
service nginx restart
