#!/usr/bin/env bash
# Install HA proxy and configure it

# Installing HAProxy
apt-get update

apt-get -y install haproxy

# Starting HAProxy
service haproxy start

# Configuration

current_conf="/etc/haproxy/haproxy.cfg"

new_conf="
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
frontend web_front
    bind *:80
    default_backend web_back
backend web_back
    balance roundrobin
    server 333082-web-01 107.22.144.84:80 check
    server 333082-web-02 52.86.231.250:80 check
"
echo "$new_conf" > "$current_conf"

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

service haproxy restart
