#!/usr/bin/env bash
# Install HA proxy and configure it

# Installing HAProxy
apt-get update

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8

apt-get -y install haproxy=2.8.\*

# Starting HAProxy
service haproxy start

# Configuration

current_conf="/etc/haproxy/haproxy.cfg"

new_conf="
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend web_front
    bind *:80
    default_backend web_back

backend web_back
    balance random
    server 333082-web-01 107.22.144.84:80 check
    server 333082-web-02 52.86.231.250:80 check
"
echo "$new_conf" > "$current_conf"

service haproxy restart
update-rc.d haproxy defaults
