#!/usr/bin/env bash
# Install HA proxy and configure it
sudo apt-get -y update
sudo apt-get -y install haproxy

# Editing the HAProxy config file
echo "
frontend  dohoudaniel-frontend
        bind *:80
        mode http
        default_backend dohoudaniel-backend
backend dohoudaniel-backend
        balance roundrobin
        server 125427-web-01 18.210.18.189:80 check
        server 125427-web-02 100.26.120.45:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# Restarting the HAProxy service
sudo service haproxy restart
