#!/usr/bin/env bash
# A Bash script that configures a Docker image to listen on port 80 for an Nginx installation
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
