#!/usr/bin/env bash
# A Bash script that configures a Docker image to listen on port 80 for an Nginx installation
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
