#!/usr/bin/env bash
# Displays "bad luck" on 4th
#+ "good luck" on 8th
#+ "Best school for the rest

i="1"

while [ $i -le "10" ];
do
    if [ $i -eq "4" ];
    then
        echo "bad luck"
    elif [ $i -eq "8" ];
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
