#!/usr/bin/env bash
#Displays good luck and bad luck

count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
		count=$((count + 1))
done
