#!/usr/bin/env bash
# Displays numbers from 1 to 20 but
#+ Displays "bad luck from china" after 4th
#+ "bad luck from japan" after 9th
#+ "bad luck from italy" after 17th

i="1"

while ((i <= 20))
do
    echo "$i"
    case $i in
        "4")
            echo "bad luck from China"
        ;;
        "9")
            echo "bad luck from Japan"
        ;;
        "17")
            echo "bad luck from Italy"
        ;;
    esac
    ((i++))
done
