#!/usr/bin/env bash

# Displays time for 12 hrs 59 mins
#+ Hours from 0 to 12
#+ Minutes from 1 to 59

i="0"

while ((i <= 12))
do
    echo "Hour: $i"

    n="1"
    while ((n <= 59))
    do
        echo "$n"
        ((n++))
    done
    ((i++))
done
